# Choreo Deployment Configuration - Optimized for Maximum Stability
apiVersion: v1
kind: Config
metadata:
  name: apilage-ai-backend
  
spec:
  # Health Check Configuration - Very lenient to prevent false failures
  healthCheck:
    path: "/api/health/live"
    port: 3000
    scheme: "HTTP"
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 8
    
  # Readiness Probe - Simple and forgiving
  readinessProbe:
    path: "/api/health/live"
    port: 3000
    scheme: "HTTP"  
    initialDelaySeconds: 45
    periodSeconds: 15
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 6
    
  # Liveness Probe - Very conservative
  livenessProbe:
    path: "/api/health/live"
    port: 3000
    scheme: "HTTP"
    initialDelaySeconds: 120
    periodSeconds: 60
    timeoutSeconds: 15
    successThreshold: 1
    failureThreshold: 10
    
  # NO RESOURCE LIMITS - Remove all restrictions
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    # NO LIMITS SPECIFIED - Let the app use what it needs
      
  # Environment Configuration
  environment:
    NODE_ENV: "production"
    PORT: "3000"
    CONTAINER: "true"
    DISABLE_MEMORY_MONITORING: "true"
    # NO NODE_OPTIONS - Removed aggressive memory settings
    
  # Container Configuration - Quick shutdown
  container:
    port: 3000
    terminationGracePeriodSeconds: 10
    
  # Scaling Configuration - Keep it simple
  scaling:
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 90
    targetMemoryUtilizationPercentage: 90