# Choreo Deployment Configuration
apiVersion: v1
kind: Config
metadata:
  name: apilage-ai-backend
  
spec:
  # Health Check Configuration
  healthCheck:
    # Primary health check endpoint
    path: "/api/health"
    port: 3000
    scheme: "HTTP"
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
    
  # Readiness Probe
  readinessProbe:
    path: "/api/health/ready"
    port: 3000
    scheme: "HTTP"  
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 3
    
  # Liveness Probe  
  livenessProbe:
    path: "/api/health/live"
    port: 3000
    scheme: "HTTP"
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
    
  # Resource Configuration
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
      
  # Environment Configuration
  environment:
    NODE_ENV: "production"
    NODE_OPTIONS: "--max-old-space-size=384 --gc-interval=100"
    PORT: "3000"
    
  # Container Configuration  
  container:
    port: 3000
    terminationGracePeriodSeconds: 30
    
  # Scaling Configuration
  scaling:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
